dataset:
  name: straightline
  augmentation: None
  loader: torch
  batch_size: 1
  num_workers: 0

run:
  n_epochs: 100
  current_epoch: 0
  store_state_path: ../checkpoints/s0/ae
  # load_state_path: ../checkpoints/s1/vq_vae_full_image/s1_2023-05-04_15-48-50.ckpt
  visualize_plots: True

optimizers:
  opt1:
    type: Adam
    params:
      lr: 0.001
      betas: [ 0.9, 0.999 ]
      eps: 0.00000001
      weight_decay: 0
      amsgrad: False
    scheduler:
      type: ReduceLROnPlateau
      params:
        mode: min
        factor: 0.1
        patience: 5
        threshold: 0.0001
        threshold_mode: rel
        cooldown: 0
        min_lr: 0.000001
        eps: 0.00000001

metrics:
  - mae:
      type: MeanAbsoluteError
      meter: avg
  - mape:
      type: MeanAbsolutePercentageError
      meter: avg
  - mse:
      type: MeanSquaredError
      meter: avg

logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "s0"
    log_model: True
    group: "autoencoder"
    job_type: "train"
  console:
    active: True

feature_extractor:
  out_channels: 4
  add_bg_channel: False
  bin_threshold: 0.  # set to 0.5 to obtain better features
  optimized_filter_lines: True # set to True to obtain better features

model:
  type: angle-predictor
  params:
    kernel_size: 5

n_alternative_cells: 1

lateral_model:
  channels: 4
  max_timesteps: 2  # 1 = only one forward pass without recurrent connection
  min_k: 2
  max_k: 3
  l1_type: 'lateral_flex'
  l1_params:
    locality_size: 5
    lr: 0.2
    hebbian_rule: 'vanilla'
    neg_corr: True
    act_threshold: 0.5  # 'bernoulli'
    square_factor: 1.2
    support_factor: 1.3