dataset:
  name: mnist
  augmentation: None
  loader: torch
  batch_size: 128
  num_workers: 0

optimizers:
  - opt1:
      type: Adam
      params:
        lr: 0.001
        betas: [0.9, 0.999]
        eps: 1e-08
        weight_decay: 0
        amsgrad: False

metrics:
  - accuracy:
      type: Accuracy
      meter: avg
      params:
        task: "multiclass"
        average: "micro"
        top_k: 1
        threshold: 0.5
  - f1:
      type: F1Score
      meter: avg
      params:
        task: "multiclass"
        average: "micro"
        top_k: 1
        threshold: 0.5