base_dir: data/

cifar10:
  dir: cifar10/
  beton_dir: beton/cifar10/
  mean: [0.4914, 0.4822, 0.4465]
  std: 0.2470, 0.2435, 0.2616]
  num_classes: 10
  num_channels: 3

mnist:
  dir: mnist/
  beton_dir: beton/mnist/
  mean: [0.1307]
  std: [0.3081]
  num_classes: 10
  num_channels: 1

imagenet:
  dir: imagenet/
  beton_dir: beton/imagenet/
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  num_classes: 1000
  num_channels: 3

augmentation_v1:
  aug1:
    - probability: 0.8
    - transformations:
      - transformation: ColorJitter
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.1
      - transformation: GaussianBlur
        kernel_size: 3
        sigma: [0.1, 2.0]
  aug2:
    - probability: 0.8
    - transformations:
      - transformation: RandomAffine
        degrees: 10
        translate: [0.1, 0.1]
        scale: [0.9, 1.1]
        shear: 10
      - transformation: RandomPerspective
        distortion_scale: 0.5
        p: 0.5


