base_dir: ../data/

cifar10:
  dir: cifar10/
  beton_dir: beton/cifar10/
  mean: [ 0.4914, 0.4822, 0.4465 ]
  std: [ 0.2470, 0.2435, 0.2616 ]
  num_classes: 10
  num_channels: 3
  img_width: 32
  img_height: 32
  train_dataset_params:
    train: True
    download: True
  test_dataset_params:
    train: False
    download: True


cifar100:
  dir: cifar100/
  beton_dir: beton/cifar100/
  mean: [ 0.5071, 0.4865, 0.4409 ]
  std: [ 0.2673, 0.2564, 0.2762 ]
  num_classes: 100
  num_channels: 3
  img_width: 32
  img_height: 32
  train_dataset_params:
    train: True
    download: True
  test_dataset_params:
    train: False
    download: True

mnist:
  dir: mnist/
  beton_dir: beton/mnist/
  mean: [ 0.1307 ]
  std: [ 0.3081 ]
  num_classes: 10
  num_channels: 1
  img_width: 28
  img_height: 28
  train_dataset_params:
    train: True
    download: True
  test_dataset_params:
    train: False
    download: True

imagenet:
  dir: imagenet/
  beton_dir: beton/imagenet/
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]
  num_classes: 1000
  num_channels: 3
  train_dataset_params:
    split: "train"
    download: True
  valid_dataset_params:
    split: "val"
    download: True
  test_dataset_params:
    split: "test"
    download: True

straightline:
  num_channels: 1
  mean: [ 0. ]
  std: [ 1. ]
  img_width: 32
  img_height: 32
  train_dataset_params:
    split: "train"
    vertical_horizontal_only: True
    aug_range: 0
    num_images: 3000
    num_aug_versions: 0
  valid_dataset_params:
    split: "val"
    vertical_horizontal_only: True
    aug_range: 0
    fixed_lines_eval_test: True
    num_images: 2
    num_aug_versions: 0
    noise: 0.0
  test_dataset_params:
    split: "test"
    vertical_horizontal_only: True
    aug_range: 0
    fixed_lines_eval_test: True
    num_images: 2
    num_aug_versions: 0
    noise: 0.0

augmentation_v1:
  aug1:
    - probability: 0.8
    - transformations:
        - transformation: ColorJitter
          params:
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
        - transformation: GaussianBlur
          params:
            kernel_size: 3
            sigma: [ 0.1, 2.0 ]
  aug2:
    - probability: 0.8
    - transformations:
        - transformation: RandomAffine
          params:
            degrees: 10
            translate: [ 0.1, 0.1 ]
            scale: [ 0.9, 1.1 ]
            shear: 10
        - transformation: RandomPerspective
          params:
            distortion_scale: 0.5
            p: 0.5


