dataset:
  name: cifar100
  augmentation: None
  loader: torch
  batch_size: 64
  num_workers: 0

run:
  load_model: None
  n_epochs: 20

optimizers:
  opt1:
    type: Adam
    params:
      lr: 0.001
      betas: [0.9, 0.999]
      eps: 0.00000001
      weight_decay: 0
      amsgrad: False

metrics:
  - accuracy:
      type: Accuracy
      meter: avg
      params:
        task: "multiclass"
        average: "micro"
        top_k: 1
        threshold: 0.5
  - f1:
      type: F1Score
      meter: avg
      params:
        task: "multiclass"
        average: "micro"
        top_k: 1
        threshold: 0.5
  - recall:
      type: Recall
      meter: avg
      params:
        task: "multiclass"
        average: "micro"
        top_k: 1
        threshold: 0.5
  - precision:
      type: Precision
      meter: avg
      params:
          task: "multiclass"
          average: "micro"
          top_k: 1
          threshold: 0.5

logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "early_commitment"
    log_model: True
    group: "test_group"
    job_type: "train"
  console:
    active: True