dataset:
  name: straightline
  augmentation: None
  loader: torch
  batch_size: 1
  num_workers: 0

run:
  n_epochs: 101
  current_epoch: 0
  plots:
    enable: True
    only_last_epoch: False
    store_path: "../tmp/test/"
  store_state_path: None
  load_state_path: None


metrics:
  - mse:
      type: MeanSquaredError
      meter: avg
  - mae:
      type: MeanAbsoluteError
      meter: avg

optimizers:
  l2_opt:
    type: Adam
    params:
      lr: 0.05
      betas: [ 0.9, 0.999 ]
      eps: 0.00000001
      weight_decay: 0
      amsgrad: False
    scheduler:
      type: ReduceLROnPlateau
      params:
        mode: min
        factor: 0.1
        patience: 5
        threshold: 0.0001
        threshold_mode: rel
        cooldown: 0
        min_lr: 0.000001
        eps: 0.00000001

logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "lateral_connections_toy_example"
    log_model: True
    group: null # "hebbian_learning"
    job_type: null # "train"
  console:
    active: True

feature_extractor:
  out_channels: 4
  add_bg_channel: False
  bin_threshold: 0.  # set to 0.5 to obtain better features
  optimized_filter_lines: True # set to True to obtain better features

n_alternative_cells: 10

lateral_model:
  channels: 4
  max_timesteps: 2  # 1 = only one forward pass without recurrent connection
  min_k: 2
  max_k: 3
  l1_type: 'lateral_flex'
  l1_params:
    locality_size: 5
    lr: 0.2
    hebbian_rule: 'vanilla'
    neg_corr: True
    act_threshold: 0.3  # 'bernoulli'
    square_factor:
    - 0.7
    - 0.9
    - 1.1
    - 1.3
    - 1.5
    - 1.7
    support_factor: 1.3

l2:
  k: 1
  n_hidden: 16