dataset:
  name: arc
  augmentation: None
  loader: torch
  batch_size: 1
  num_workers: 0

run:
  n_epochs: 15
  current_epoch: 0
  plots:
    enable: True
    only_last_epoch: False
    store_path: "../tmp/test/"
  store_state_path: None
  load_state_path: None


metrics:
  - mse:
      type: MeanSquaredError
      meter: avg
  - mae:
      type: MeanAbsoluteError
      meter: avg

optimizers:
  l2_opt:
    type: Adam
    params:
      lr: 0.05
      betas: [ 0.9, 0.999 ]
      eps: 0.00000001
      weight_decay: 0
      amsgrad: False
    scheduler:
      type: ReduceLROnPlateau
      params:
        mode: min
        factor: 0.1
        patience: 5
        threshold: 0.0001
        threshold_mode: rel
        cooldown: 0
        min_lr: 0.000001
        eps: 0.00000001

logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "lateral_connections_arc"
    log_model: True
    group: null # "hebbian_learning"
    job_type: null # "train"
  console:
    active: True

feature_extractor:
  active: False
  out_channels: 10
  add_bg_channel: False
  bin_threshold: 0.  # set to 0.5 to obtain better features
  optimized_filter_lines: True # set to True to obtain better features

n_alternative_cells: 11

lateral_model:
  channels: 10
  max_timesteps: 3  # 1 = only one forward pass without recurrent connection
  min_k: 2
  max_k: 3
  l1_type: 'lateral_flex'
  l1_params:
    locality_size: 2
    lr: 200
    hebbian_rule: 'vanilla'
    neg_corr: True
    act_threshold: 0.5  # 'bernoulli'
    square_factor: 1.5
    support_factor: 1.3

l2:
  k: 1
  n_hidden: 16