dataset:
  name: mnist
  augmentation: None
  loader: torch
  batch_size: 128
  num_workers: 0
  patch_height: 4
  patch_width: 4

run:
  load_model: None
  mode: full_image
  n_epochs: 30
  current_epoch: 0
  store_state_path: checkpoints/s1/vq_vae_full_image
  load_state_path: None

optimizers:
  opt1:
    type: Adam
    params:
      lr: 0.001
      betas: [0.9, 0.999]
      eps: 0.00000001
      weight_decay: 0
      amsgrad: False

metrics:
  - mae:
      type: MeanAbsoluteError
      meter: avg
  - mape:
      type: MeanAbsolutePercentageError
      meter: avg
  - mse:
      type: MeanSquaredError
      meter: avg

logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "test"
    log_model: True
    group: "test_group"
    job_type: "train"
  console:
    active: True

model:
  type: "SmallVQVAE"
  params:
    num_hiddens: 16
    num_embeddings: 4
    embedding_dim: 16
