dataset:
  name: straightline
  augmentation: None
  loader: torch
  batch_size: 128
  num_workers: 0

run:
  n_epochs: 2
  current_epoch: 0
  plots:
    enable: True
    only_last_epoch: False
    store_path: "../tmp/test/"
  store_state_path: None
  load_state_path: None


logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "lateral_connections_toy_example"
    log_model: True
    group: "hebbian_learning"
    job_type: "train"
  console:
    active: True

feature_extractor:
  out_channels: 4

lateral_model:
  max_timesteps: 3
  l1_params:
    out_channels: 4
    locality_size: 2
    lr: 0.0005
    mask_out_bg: False
    mov_avg_rate_prev_view: 0.
    mov_avg_rate_prev_time: 0.
    mov_avg_rate_prev: 0.
    hebbian_rule: 'instar'
    use_bias: True
    k: 1
    thr_rate: 0.05
    target_rate: null
    w_init: 'random'