dataset:
  name: straightline
  augmentation: None
  loader: torch
  batch_size: 1
  num_workers: 0

run:
  n_epochs: 100
  current_epoch: 0
  visualize_plots: False


logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "lateral_connections_toy_example"
    log_model: True
    group: "hebbian_learning"
    job_type: "train"
  console:
    active: True

feature_extractor:
  out_channels: 4

lateral_model:
  locality_size: 2
  alpha: 0.09 #0.905
  lr: 0.001
  channels: 64
  max_timesteps: 5  # 2000
  change_threshold: 0.00001