dataset:
  name: straightline
  augmentation: None
  loader: torch
  batch_size: 128
  num_workers: 0

run:
  n_epochs: 2
  current_epoch: 0
  plots:
    enable: True
    only_last_epoch: False
    store_path: "../tmp/test/"
  store_state_path: None
  load_state_path: None


logging:
  wandb:
    active: False,
    save_dir: "../wandb"
    project: "lateral_connections_toy_example"
    log_model: True
    group: "hebbian_learning"
    job_type: "train"
  console:
    active: True

feature_extractor:
  out_channels: 4
  add_bg_channel: False

lateral_model:
  channels: 4
  max_timesteps: 5
  l1_params:
    locality_size: 2
    lr: 0.00005
    mask_out_bg: False
    mov_avg_rate_prev_view: 0.
    mov_avg_rate_prev_time: 0.
    mov_avg_rate_prev: 0.
    hebbian_rule: 'instar'
    use_bias: False
    k: 1
    thr_rate: 0.05
    target_rate: [0.05, 0.05, 0.05, 0.05, 0.8] #null
    w_init: 'identity'